#!/bin/sh
apt -qq install dos2linux
##make sure linux readable files - caused problems in past
echo "Making sure all files are Linux readabel"  | wall -n 
`find $(pwd)/custom_extras/cfg/ -type f -print0 | xargs -0 dos2unix --`
`find $(pwd)/templates/ -type f -print0 | xargs -0 dos2unix --`
echo "Starting ISO build with custom install files..!"  | wall -n 
build-simple-cdd --conf sda-atomic.conf --dvd --force-root 
echo "Build complete, see images folder for ISO..!"  | wall -n
